
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 20 20:50:08 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 22;
  public static final int CHAR = 34;
  public static final int LESSE = 42;
  public static final int GREATER = 39;
  public static final int LPAREN = 24;
  public static final int SEMI = 5;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 11;
  public static final int LESS = 41;
  public static final int FOR = 16;
  public static final int MINUS = 27;
  public static final int RPAREN = 25;
  public static final int AND = 32;
  public static final int OR = 31;
  public static final int COMMA = 44;
  public static final int CLASS = 8;
  public static final int INC = 29;
  public static final int DIV = 46;
  public static final int PLUS = 26;
  public static final int ASSIGN = 23;
  public static final int IF = 14;
  public static final int BOOLEAN = 35;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 37;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 45;
  public static final int MOD = 47;
  public static final int GREATERE = 40;
  public static final int NUMBER = 33;
  public static final int IDENT = 36;
  public static final int BREAK = 17;
  public static final int VOID = 13;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int LSQUARE = 6;
  public static final int ENUM = 10;
  public static final int READ = 20;
  public static final int RSQUARE = 7;
  public static final int NEQUAL = 38;
  public static final int RBRACE = 4;
  public static final int FULLSTOP = 43;
  public static final int EXTENDS = 9;
  public static final int PROG = 2;
  public static final int DEC = 30;
  public static final int IMPLEMENTS = 12;
  public static final int PRINT = 21;
}

